apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditservice
  template:
    metadata:
      labels:
        app: auditservice
    spec:
      containers:
      - name: auditservice
        image: chaincustody-auditservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/audit_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpass