apiVersion: apps/v1
kind: Deployment
metadata:
  name: custodyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custodyservice
  template:
    metadata:
      labels:
        app: custodyservice
    spec:
      containers:
      - name: custodyservice
        image: chaincustody-custodyservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/custody_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpass